definitions:
  main.Item:
    properties:
      description:
        example: Sepatu Nike
        type: string
      item_id:
        example: "123"
        type: string
      quantity:
        example: 1
        type: integer
    type: object
  main.Order:
    properties:
      customer_name:
        example: Ali
        type: string
      items:
        $ref: '#/definitions/main.Item'
      order_at:
        example: 2006-01-02T15:04:05Z07:00
        type: string
      order_id:
        example: ABC
        type: string
    type: object
host: localhost:8083
info:
  contact:
    name: sandyverden@gmail.com
  description: This is a sample server for API Kampus Merdeka
  title: Kampus Merdeka API Docs
  version: "1.1"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all  order with input on payload
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
      summary: Get all order
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create new order with input on payload
      parameters:
      - description: Create Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/main.Order'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
      summary: Create a new order
      tags:
      - orders
  /orders/{orderId}:
    get:
      consumes:
      - application/json
      description: Get all  order with input on payload
      parameters:
      - description: Id Order
        in: path
        name: orderId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
      summary: Get all order
      tags:
      - orders
swagger: "2.0"
